#!/usr/bin/env tsx
// scripts/precompute-merkle.ts
// Run: npx tsx scripts/precompute-merkle.ts
// Writes src/lib/sample-root.ts with the precomputed Merkle root.
// This guarantees the shipped `SAMPLE_ROOT` matches what verifyReceipt() computes.

import { writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Minimal Node.js SHA-256 using built-in crypto
import { createHash } from 'crypto';

function sha256Node(input: string): string {
  return createHash('sha256').update(input, 'utf8').digest('hex');
}

// Import transcript
const { SAMPLE_TRANSCRIPT } = await import('../src/lib/sample-transcript.js');

console.log('[Agora Precompute] Hashing leaves...');

let leaves: string[] = SAMPLE_TRANSCRIPT.map((t: string, i: number) => {
  const h = sha256Node(t);
  console.log(`  leaf[${i}] = 0x${h.slice(0, 16)}...`);
  return h;
});

// Build tree bottom-up
let level = leaves;
let depth = 0;
while (level.length > 1) {
  const next: string[] = [];
  for (let i = 0; i < level.length; i += 2) {
    const a = level[i];
    const b = level[i + 1] ?? level[i];
    const parent = sha256Node(a + b);
    console.log(`  depth ${depth} parent = 0x${parent.slice(0, 16)}...`);
    next.push(parent);
  }
  level = next;
  depth++;
}

const root = level[0];
console.log(`\n[Agora Precompute] Root = 0x${root}`);

const outPath = join(__dirname, '../src/lib/sample-root.ts');
writeFileSync(outPath, `// AUTO-GENERATED by scripts/precompute-merkle.ts — do not edit manually\nexport const SAMPLE_ROOT = '${root}';\n`);
console.log(`[Agora Precompute] Written to ${outPath}`);
