// This file is generated by scripts/generate_frontend_api_types.py.
// Do not edit by hand.

export type MechanismName = "debate" | "vote" | "delphi";
export type TaskStatusName = "pending" | "in_progress" | "completed" | "failed" | "paid";
export type PaymentStatusName = "locked" | "released" | "none";
export type AuthMethodName = "jwt" | "api_key";
export type ApiKeyScopeName = "tasks:read" | "tasks:write" | "benchmarks:read" | "benchmarks:write" | "api_keys:read" | "api_keys:write";

export interface ReasoningPresetOverrides {
  gemini_pro: "low" | "high" | null;
  gemini_flash: "low" | "medium" | "high" | null;
  openrouter: "low" | "medium" | "high" | null;
  claude: "low" | "medium" | "high" | null;
}

export interface ReasoningPresets {
  gemini_pro: "low" | "high";
  gemini_flash: "low" | "medium" | "high";
  openrouter: "low" | "medium" | "high";
  claude: "low" | "medium" | "high";
}

export interface TaskCreateRequest {
  task: string;
  agent_count: number;
  stakes: number;
  mechanism_override: "debate" | "vote" | "delphi" | null;
  allow_mechanism_switch: boolean;
  allow_offline_fallback: boolean;
  quorum_threshold: number;
  reasoning_presets: ReasoningPresetOverrides | null;
  tier_model_overrides: RuntimeTierModelOverrides | null;
  source_urls: Array<string>;
  source_file_ids: Array<string>;
  enable_tools: boolean;
  tool_policy: ToolPolicy | null;
}

export interface RuntimeTierModelOverrides {
  pro: string | null;
  flash: string | null;
  openrouter: string | null;
  claude: string | null;
}

export interface ToolPolicy {
  enabled: boolean;
  allow_search: boolean;
  allow_url_analysis: boolean;
  allow_file_analysis: boolean;
  allow_code_execution: boolean;
  max_tool_calls_per_agent: number;
  max_urls_per_call: number;
  max_files_per_call: number;
  execution_timeout_seconds: number;
}

export interface TaskEvent {
  event: string;
  data: Record<string, unknown>;
  timestamp: string | null;
}

export interface DeliberationResultResponse {
  task_id: string;
  mechanism: "debate" | "vote" | "delphi";
  final_answer: string;
  confidence: number;
  quorum_reached: boolean;
  merkle_root: string | null;
  decision_hash: string | null;
  agent_count: number;
  agent_models_used: Array<string>;
  model_token_usage: Record<string, number>;
  model_latency_ms: Record<string, number>;
  model_telemetry: Record<string, ModelTelemetryResponse>;
  total_tokens_used: number;
  reasoning_presets: ReasoningPresets | null;
  input_tokens_used: number | null;
  output_tokens_used: number | null;
  thinking_tokens_used: number | null;
  latency_ms: number;
  cost: BenchmarkCostEstimateResponse | null;
  payment_amount: number;
  payment_status: "locked" | "released" | "none";
  informational_model_payouts: Record<string, number>;
  round_count: number;
  mechanism_switches: number;
  transcript_hashes: Array<string>;
  convergence_history: Array<Record<string, unknown>>;
  locked_claims: Array<Record<string, unknown>>;
  mechanism_trace: Array<Record<string, unknown>>;
  execution_mode: string;
  selector_source: string;
  selector_fallback_path: Array<string>;
  fallback_count: number;
  fallback_events: Array<Record<string, unknown>>;
  mechanism_override_source: string | null;
  sources: Array<TaskSourceResponse>;
  tool_usage_summary: ToolUsageSummaryResponse | null;
  evidence_items: Array<EvidenceItemResponse>;
  citation_items: Array<CitationItemResponse>;
}

export interface BenchmarkCostEstimateResponse {
  estimated_cost_usd: number | null;
  model_estimated_costs_usd: Record<string, number>;
  pricing_version: string | null;
  estimated_at: string | null;
  estimation_mode: "exact" | "approx_total_tokens" | "unavailable" | "mixed" | null;
  pricing_sources: Record<string, string>;
}

export interface CitationItemResponse {
  title: string;
  url: string | null;
  domain: string | null;
  rank: number | null;
  source_kind: "text_file" | "code_file" | "pdf" | "image" | "url" | null;
  source_id: string | null;
  note: string | null;
}

export interface EvidenceItemResponse {
  evidence_id: string;
  tool_name: string;
  agent_id: string;
  summary: string;
  round_index: number;
  source_ids: Array<string>;
  citations: Array<CitationItemResponse>;
}

export interface ModelTelemetryResponse {
  total_tokens: number;
  input_tokens: number | null;
  output_tokens: number | null;
  thinking_tokens: number | null;
  latency_ms: number;
  estimated_cost_usd: number | null;
  estimation_mode: "exact" | "approx_total_tokens" | "unavailable" | "mixed" | null;
}

export interface TaskSourceResponse {
  source_id: string;
  kind: "text_file" | "code_file" | "pdf" | "image" | "url";
  display_name: string;
  mime_type: string;
  size_bytes: number;
  sha256: string | null;
  status: "pending_upload" | "uploaded" | "ready" | "failed";
  created_at: string;
  source_url: string | null;
}

export interface ToolUsageSummaryResponse {
  total_tool_calls: number;
  successful_tool_calls: number;
  failed_tool_calls: number;
  tool_counts: Record<string, number>;
}

export interface TaskStatusResponse {
  task_id: string;
  task_text: string;
  workspace_id: string;
  created_by: string;
  mechanism: "debate" | "vote" | "delphi";
  mechanism_override: "debate" | "vote" | "delphi" | null;
  allow_mechanism_switch: boolean;
  allow_offline_fallback: boolean;
  quorum_threshold: number;
  execution_source: "hosted" | "local_byok";
  background_recovery_allowed: boolean;
  enable_tools: boolean;
  tool_policy: ToolPolicy | null;
  source_urls: Array<string>;
  source_file_ids: Array<string>;
  sources: Array<TaskSourceResponse>;
  selector_source: string;
  selector_fallback_path: Array<string>;
  mechanism_override_source: string | null;
  status: "pending" | "in_progress" | "completed" | "failed" | "paid";
  selector_reasoning: string;
  selector_reasoning_hash: string;
  selector_confidence: number;
  merkle_root: string | null;
  decision_hash: string | null;
  quorum_reached: boolean | null;
  agent_count: number;
  reasoning_presets: ReasoningPresets;
  tier_model_overrides: RuntimeTierModelOverrides | null;
  round_count: number;
  mechanism_switches: number;
  transcript_hashes: Array<string>;
  solana_tx_hash: string | null;
  explorer_url: string | null;
  payment_amount: number;
  payment_status: "locked" | "released" | "none";
  chain_operations: Record<string, ChainOperationRecord>;
  created_at: string;
  updated_at: string;
  completed_at: string | null;
  stop_requested_at: string | null;
  failure_reason: string | null;
  latest_error_event: TaskEvent | null;
  result: DeliberationResultResponse | null;
  events: Array<TaskEvent>;
}

export interface ChainOperationRecord {
  status: "pending" | "succeeded" | "failed";
  tx_hash: string | null;
  explorer_url: string | null;
  error: string | null;
  attempts: number;
  updated_at: string;
}

export interface PrincipalResponse {
  auth_method: "jwt" | "api_key";
  workspace_id: string;
  user_id: string | null;
  display_name: string;
  email: string;
  scopes: Array<"tasks:read" | "tasks:write" | "benchmarks:read" | "benchmarks:write" | "api_keys:read" | "api_keys:write">;
  api_key_id: string | null;
}

export interface WorkspaceResponse {
  id: string;
  display_name: string;
  kind: "personal";
  owner_user_id: string;
  created_at: string;
}

export interface FeatureFlagsResponse {
  benchmarks_visible: boolean;
  api_keys_visible: boolean;
}

export interface AuthMeResponse {
  principal: PrincipalResponse;
  workspace: WorkspaceResponse;
  feature_flags: FeatureFlagsResponse;
}

export interface ApiKeyMetadataResponse {
  key_id: string;
  workspace_id: string;
  name: string;
  public_id: string;
  scopes: Array<"tasks:read" | "tasks:write" | "benchmarks:read" | "benchmarks:write" | "api_keys:read" | "api_keys:write">;
  created_by_user_id: string;
  created_at: string;
  last_used_at: string | null;
  expires_at: string | null;
  revoked_at: string | null;
}

export interface ApiKeyCreateResponse {
  api_key: string;
  metadata: ApiKeyMetadataResponse;
}

export interface TaskCreateResponse {
  task_id: string;
  mechanism: "debate" | "vote" | "delphi";
  confidence: number;
  reasoning: string;
  selector_reasoning_hash: string;
  status: "pending" | "in_progress" | "completed" | "failed" | "paid";
  selector_source: string;
  selector_fallback_path: Array<string>;
  mechanism_override_source: string | null;
}

export interface BenchmarkRunRequest {
  training_per_category: number;
  holdout_per_category: number;
  agent_count: number;
  live_agents: boolean;
  seed: number;
  domain_prompts: Record<string, BenchmarkDomainPrompt>;
  reasoning_presets: ReasoningPresetOverrides | null;
  tier_model_overrides: RuntimeTierModelOverrides | null;
  local_models: Array<LocalModelSpec> | null;
  local_provider_keys: LocalProviderKeys | null;
  local_debate_config: LocalDebateConfig | null;
}

export interface BenchmarkDomainPrompt {
  template_id: string | null;
  question: string | null;
  source: "template" | "custom";
}

export interface LocalDebateConfig {
  devils_advocate_model: LocalModelSpec | null;
  devils_advocate_fallback_models: Array<LocalModelSpec> | null;
}

export interface LocalModelSpec {
  provider: "gemini" | "anthropic" | "openrouter";
  model: string;
  reasoning_preset: string | null;
}

export interface LocalProviderKeys {
  gemini_api_key: string | null;
  anthropic_api_key: string | null;
  openrouter_api_key: string | null;
}

export interface BenchmarkRunResponse {
  run_id: string;
  status: "queued" | "running" | "completed" | "failed";
  created_at: string;
}

export interface BenchmarkRunStatusResponse {
  run_id: string;
  status: "queued" | "running" | "completed" | "failed";
  created_at: string;
  updated_at: string;
  error: string | null;
  artifact_id: string | null;
  execution_source: "hosted" | "local_byok";
  background_recovery_allowed: boolean;
  request: BenchmarkStoredRequest | null;
  reasoning_presets: ReasoningPresets | null;
  tier_model_overrides: RuntimeTierModelOverrides | null;
  latest_mechanism: string | null;
  agent_count: number | null;
  total_tokens: number | null;
  thinking_tokens: number | null;
  total_latency_ms: number | null;
  model_telemetry: Record<string, ModelTelemetryResponse>;
  cost: BenchmarkCostEstimateResponse | null;
  completed_item_count: number;
  failed_item_count: number;
  degraded_item_count: number;
  failure_counts_by_category: Record<string, number>;
  failure_counts_by_reason: Record<string, number>;
  failure_counts_by_stage: Record<string, number>;
}

export interface BenchmarkStoredRequest {
  training_per_category: number;
  holdout_per_category: number;
  agent_count: number;
  live_agents: boolean;
  seed: number;
  domain_prompts: Record<string, BenchmarkDomainPrompt>;
  reasoning_presets: ReasoningPresets | null;
  tier_model_overrides: RuntimeTierModelOverrides | null;
  resolved_domain_prompts: Record<string, ResolvedBenchmarkDomainPrompt>;
}

export interface ResolvedBenchmarkDomainPrompt {
  template_id: string;
  template_title: string;
  source: "template" | "custom";
  question: string;
}

export interface BenchmarkCatalogResponse {
  global_recent: Array<BenchmarkCatalogEntry>;
  global_frequency: Array<BenchmarkCatalogEntry>;
  global_tests_recent: Array<BenchmarkRunStatusResponse>;
  global_tests_frequency: Array<BenchmarkRunStatusResponse>;
  user_recent: Array<BenchmarkCatalogEntry>;
  user_frequency: Array<BenchmarkCatalogEntry>;
  user_tests_recent: Array<BenchmarkRunStatusResponse>;
  user_tests_frequency: Array<BenchmarkRunStatusResponse>;
}

export interface BenchmarkCatalogEntry {
  artifact_id: string;
  scope: "global" | "user";
  owner_user_id: string | null;
  source: string;
  created_at: string;
  run_count: number;
  mechanism_counts: Record<string, number>;
  model_counts: Record<string, number>;
  frequency_score: number;
  status: string | null;
  latest_mechanism: string | null;
  agent_count: number | null;
  total_tokens: number;
  thinking_tokens: number;
  total_latency_ms: number;
  models: Array<string>;
  model_telemetry: Record<string, ModelTelemetryResponse>;
  cost: BenchmarkCostEstimateResponse | null;
}

export interface BenchmarkDetailResponse {
  benchmark_id: string;
  artifact_id: string | null;
  scope: "global" | "user";
  source: string;
  status: string | null;
  owner_user_id: string | null;
  created_at: string;
  updated_at: string;
  run_count: number;
  mechanism_counts: Record<string, number>;
  model_counts: Record<string, number>;
  frequency_score: number;
  latest_mechanism: string | null;
  agent_count: number | null;
  total_tokens: number;
  thinking_tokens: number;
  total_latency_ms: number;
  models: Array<string>;
  run_id: string | null;
  execution_source: "hosted" | "local_byok";
  background_recovery_allowed: boolean;
  request: BenchmarkStoredRequest | null;
  reasoning_presets: ReasoningPresets | null;
  tier_model_overrides: RuntimeTierModelOverrides | null;
  model_telemetry: Record<string, ModelTelemetryResponse>;
  events: Array<TaskEvent>;
  summary: BenchmarkSummaryResponse;
  benchmark_payload: Record<string, unknown>;
  cost: BenchmarkCostEstimateResponse | null;
  benchmark_items: Array<BenchmarkItemResponse>;
  active_item_id: string | null;
  active_item: BenchmarkItemResponse | null;
  completed_item_count: number;
  failed_item_count: number;
  degraded_item_count: number;
  failure_counts_by_category: Record<string, number>;
  failure_counts_by_reason: Record<string, number>;
  failure_counts_by_stage: Record<string, number>;
}

export interface BenchmarkItemResponse {
  item_id: string;
  item_index: number;
  task_index: number;
  phase: string | null;
  run_kind: string | null;
  category: string;
  question: string;
  source_task: string | null;
  status: "queued" | "running" | "completed" | "failed" | "degraded";
  mechanism: string | null;
  selector_source: string | null;
  selector_fallback_path: Array<string>;
  failure_reason: string | null;
  latest_error_event: TaskEvent | null;
  fallback_events: Array<Record<string, unknown>>;
  total_tokens: number;
  thinking_tokens: number;
  total_latency_ms: number;
  model_telemetry: Record<string, ModelTelemetryResponse>;
  summary: Record<string, unknown>;
  started_at: string | null;
  completed_at: string | null;
  events: Array<TaskEvent>;
}

export interface BenchmarkSummaryResponse {
  per_mode: Record<string, BenchmarkMetricSummaryResponse>;
  per_mechanism: Record<string, BenchmarkMetricSummaryResponse>;
  per_category: Record<string, Record<string, BenchmarkMetricSummaryResponse>>;
  per_category_by_mechanism: Record<string, Record<string, BenchmarkMetricSummaryResponse>>;
  completed_run_count: number;
  failed_run_count: number;
  degraded_run_count: number;
  scored_run_count: number;
  proxy_run_count: number;
  failure_counts_by_category: Record<string, number>;
  failure_counts_by_reason: Record<string, number>;
  failure_counts_by_stage: Record<string, number>;
}

export interface BenchmarkMetricSummaryResponse {
  accuracy: number;
  avg_tokens: number;
  avg_thinking_tokens: number;
  avg_latency_ms: number;
  avg_estimated_cost_usd: number;
  run_count: number;
  scored_run_count: number;
  proxy_run_count: number;
}

export interface BenchmarkItemEventsResponse {
  benchmark_id: string;
  item_id: string;
  events: Array<TaskEvent>;
}

export interface BenchmarkPromptTemplatesResponse {
  domains: Record<string, Array<BenchmarkPromptTemplate>>;
}

export interface BenchmarkPromptTemplate {
  id: string;
  title: string;
  question: string;
}

export interface DeliberationRuntimeConfigResponse {
  model_catalog_version: string;
  model_catalog_checked_at: string;
  participant_cycle: Array<"pro" | "flash" | "openrouter" | "claude">;
  default_reasoning_presets: ReasoningPresets;
  tiers: Record<string, RuntimeTierConfigResponse>;
  catalog: Record<string, Array<RuntimeModelOptionResponse>>;
}

export interface RuntimeModelOptionResponse {
  provider_family: "gemini" | "anthropic" | "openrouter";
  model_id: string;
  display_name: string;
  source_url: string;
  stability_tier: "stable" | "candidate" | "legacy";
  allowed_tiers: Array<"pro" | "flash" | "openrouter" | "claude">;
  supports_streaming: boolean;
  supports_json_schema: boolean;
  supports_reasoning: boolean;
  supports_reasoning_continuation: boolean;
  input_usd_per_million: number | null;
  output_usd_per_million: number | null;
  usage_telemetry_mode: string;
}

export interface RuntimeTierConfigResponse {
  tier: "pro" | "flash" | "openrouter" | "claude";
  provider_family: "gemini" | "anthropic" | "openrouter";
  model_id: string;
  display_name: string;
  vote_role: string;
  debate_role: string;
}
