// This file is generated by scripts/generate_frontend_api_types.py.
// Do not edit by hand.

export type MechanismName = "debate" | "vote";
export type TaskStatusName = "pending" | "in_progress" | "completed" | "failed" | "paid";
export type PaymentStatusName = "locked" | "released" | "none";
export type AuthMethodName = "jwt" | "api_key";
export type ApiKeyScopeName = "tasks:read" | "tasks:write" | "api_keys:read" | "api_keys:write";

export interface TaskEvent {
  event: string;
  data: Record<string, unknown>;
  timestamp: string | null;
}

export interface DeliberationResultResponse {
  task_id: string;
  mechanism: "debate" | "vote";
  final_answer: string;
  confidence: number;
  quorum_reached: boolean;
  merkle_root: string | null;
  decision_hash: string | null;
  agent_count: number;
  agent_models_used: Array<string>;
  model_token_usage: Record<string, number>;
  model_latency_ms: Record<string, number>;
  total_tokens_used: number;
  latency_ms: number;
  payment_amount: number;
  payment_status: "locked" | "released" | "none";
  informational_model_payouts: Record<string, number>;
  round_count: number;
  mechanism_switches: number;
  transcript_hashes: Array<string>;
  convergence_history: Array<Record<string, unknown>>;
  locked_claims: Array<Record<string, unknown>>;
}

export interface TaskStatusResponse {
  task_id: string;
  task_text: string;
  workspace_id: string;
  created_by: string;
  mechanism: "debate" | "vote";
  mechanism_override: "debate" | "vote" | null;
  status: "pending" | "in_progress" | "completed" | "failed" | "paid";
  selector_reasoning: string;
  selector_reasoning_hash: string;
  selector_confidence: number;
  merkle_root: string | null;
  decision_hash: string | null;
  quorum_reached: boolean | null;
  agent_count: number;
  round_count: number;
  mechanism_switches: number;
  transcript_hashes: Array<string>;
  solana_tx_hash: string | null;
  explorer_url: string | null;
  payment_amount: number;
  payment_status: "locked" | "released" | "none";
  created_at: string;
  completed_at: string | null;
  result: DeliberationResultResponse | null;
  events: Array<TaskEvent>;
}

export interface PrincipalResponse {
  auth_method: "jwt" | "api_key";
  workspace_id: string;
  user_id: string | null;
  display_name: string;
  email: string;
  scopes: Array<"tasks:read" | "tasks:write" | "api_keys:read" | "api_keys:write">;
  api_key_id: string | null;
}

export interface WorkspaceResponse {
  id: string;
  display_name: string;
  kind: "personal";
  owner_user_id: string;
  created_at: string;
}

export interface FeatureFlagsResponse {
  benchmarks_visible: boolean;
  api_keys_visible: boolean;
}

export interface AuthMeResponse {
  principal: PrincipalResponse;
  workspace: WorkspaceResponse;
  feature_flags: FeatureFlagsResponse;
}

export interface ApiKeyMetadataResponse {
  key_id: string;
  workspace_id: string;
  name: string;
  public_id: string;
  scopes: Array<"tasks:read" | "tasks:write" | "api_keys:read" | "api_keys:write">;
  created_by_user_id: string;
  created_at: string;
  last_used_at: string | null;
  expires_at: string | null;
  revoked_at: string | null;
}

export interface ApiKeyCreateResponse {
  api_key: string;
  metadata: ApiKeyMetadataResponse;
}

export interface TaskCreateResponse {
  task_id: string;
  mechanism: "debate" | "vote";
  confidence: number;
  reasoning: string;
  selector_reasoning_hash: string;
  status: "pending" | "in_progress" | "completed" | "failed" | "paid";
}
