substitutions:
  _IMAGE: us-central1-docker.pkg.dev/even-ally-480821-f3/agora/agora-api:latest

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - api/Dockerfile
      - -t
      - ${_IMAGE}
      - .

images:
  - ${_IMAGE}
