substitutions:
  _REGION: us-central1
  _REPOSITORY: agora
  _SERVICE: agora-api
  _TAG: latest

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - api/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:${_TAG}
